'use client';
import { useState } from 'react';
import { ChevronDown } from 'lucide-react';
import { toast } from 'sonner';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { NativeSelect, NativeSelectOption } from '@/components/ui/native-select';
import { Dialog, DialogContent, DialogHeader, DialogTitle, DialogDescription } from '@/components/ui/dialog';
import { type CardioEntry, type TrainingState, type WaistEntry, localDate, uid } from '../domain/training-types';
import { performedDuration, performedDistance, workoutLiftingVolume, strengthRecords, convertWeight } from '../domain/training-metrics';
import { activityRows, activityTotals, readableNumber as num, validMeasurementDate } from '../domain/training-workflow';
const labels:Record<string,string>={run:'Runs',ruck:'Rucks',bike:'Bike',row:'Row',swim:'Swim',circuit:'Circuits',mobility:'Mobility',walk:'Walks',hike:'Hikes',force:'FORCE',soccer:'Soccer',grappling:'Grappling',yoga:'Yoga',other:'Other'};

export function ActivityHistory({state,onChangeActivityType}:{state:TrainingState;onChangeActivityType:(workoutId:string,activityId:string,type:CardioEntry['activityType'])=>void}) {
 const [type,setType]=useState('run'); const [range,setRange]=useState('30'); const [limit,setLimit]=useState(20);
 const since=new Date();since.setDate(since.getDate()-Number(range)+1);
 const rows=activityRows(state,type,range==='all'?'':localDate(since),localDate()); const totals=activityTotals(rows);
 // Weekly totals are volume, not speed or fitness estimates.
 const weekly=Array.from({length:4},(_,i)=>{const end=new Date();end.setDate(end.getDate()-(3-i)*7);const start=new Date(end);start.setDate(start.getDate()-6);return {label:`${localDate(start).slice(5)}–${localDate(end).slice(5)}`,minutes:activityTotals(activityRows(state,type,localDate(start),localDate(end))).minutes};});
 const max=Math.max(1,...weekly.map(w=>w.minutes));
 const correctCategory=(workoutId:string,activityId:string,value:string)=>{
  const next=value as CardioEntry['activityType'];
  onChangeActivityType(workoutId,activityId,next);
  setType(next);
  setLimit(20);
  toast.success(`Moved to ${labels[next]}`);
 };
 return <details className="page-disclosure"><summary><span>Activity histories<small>Runs, rucks, bike, circuits and more</small></span><ChevronDown/></summary><div className="feature-panel"><div className="feature-fields"><label className="field-label">Activity<NativeSelect value={type} onChange={e=>{setType(e.target.value);setLimit(20);}}>{Object.entries(labels).map(([k,v])=><NativeSelectOption key={k} value={k}>{v}</NativeSelectOption>)}</NativeSelect></label><label className="field-label">Period<NativeSelect value={range} onChange={e=>{setRange(e.target.value);setLimit(20);}}><NativeSelectOption value="30">Last 30 days</NativeSelectOption><NativeSelectOption value="90">Last 90 days</NativeSelectOption><NativeSelectOption value="all">All history</NativeSelectOption></NativeSelect></label></div><p className="feature-note">{new Set(rows.map(r=>r.workout.id)).size} sessions · {num(totals.minutes)} min · {num(totals.distance)} km{type==='ruck' ? ` · ${num(totals.ruckKgKm)} kg·km pack load × distance` : ''}{(type==='run'||type==='ruck')&&totals.ascent>0?` · ${num(totals.ascent)} m ascent`:''}</p><details className="feature-details"><summary>Weekly time · last 28 days</summary><div className="feature-bars">{weekly.map(w=><div key={w.label}><span>{w.label}</span><i style={{width:`${Math.max(1,w.minutes/max*100)}%`}}/><strong>{num(w.minutes)} min</strong></div>)}</div></details>{rows.slice(0,limit).map(({workout:w,activity:a})=><details className="feature-details" key={a.id}><summary><span>{w.date} · {a.name}<small>{performedDuration(a)!==null?`${num(performedDuration(a)!)} min`:'Time not recorded'}{performedDistance(a)!==null?` · ${num(performedDistance(a)!)} km`:''}</small></span><ChevronDown/></summary><p>{w.name}{w.hyrox?' · HYROX segment; split includes transition':''}</p><label className="field-label">Category<NativeSelect value={a.activityType} onChange={event=>correctCategory(w.id,a.id,event.target.value)} aria-label={`Category for ${a.name}`} className="mt-1 w-full">{Object.entries(labels).map(([key,label])=><NativeSelectOption key={key} value={key}>{label}</NativeSelectOption>)}</NativeSelect></label>{a.pace&&<p>Pace: {a.pace}</p>}{a.averageHr!==null&&<p>Average HR: {a.averageHr} bpm</p>}{a.elevationM!==null&&<p>Total ascent: {num(a.elevationM)} m</p>}{a.ruckLoad!==null&&<p>Pack: {a.ruckLoad} {a.ruckLoadUnit}</p>}{a.intensity&&<p>{a.intensity}</p>}{a.intervals&&<p>{a.intervals}</p>}{a.notes&&<p>Your notes: {a.notes}</p>}</details>)}{!rows.length&&<p className="feature-note">No completed {labels[type].toLowerCase()} in this period.</p>}{rows.length>limit&&<Button variant="outline" onClick={()=>setLimit(limit+20)}>Show more</Button>}</div></details>;
}

export function DailyReview({state,onOpen}:{state:TrainingState;onOpen:(id:string)=>void}){
 const [date,setDate]=useState(localDate());
 const workouts=state.workouts.filter(w=>w.status==='completed'&&w.date===date).sort((a,b)=>(a.startedAt??a.createdAt).localeCompare(b.startedAt??b.createdAt));
 const sets=workouts.flatMap(w=>w.exercises.flatMap(e=>e.sets.filter(s=>s.completed&&!s.warmup))).length;
 const volume=workouts.reduce((sum,w)=>sum+workoutLiftingVolume(w,state.settings.defaultUnit).volume,0);
 const rows=activityRows(state,undefined,date,date);const types=[...new Set(rows.map(r=>r.activity.activityType))];
 return <details className="page-disclosure"><summary><span>Daily training summary<small>All completed sessions on one local date</small></span><ChevronDown/></summary><div className="feature-panel"><label className="field-label">Training date<Input type="date" value={date} onChange={e=>setDate(e.target.value)}/></label><p className="feature-note">{workouts.length} sessions · {sets} working sets · {num(volume)} {state.settings.defaultUnit} lifting volume</p>{types.map(type=>{const totals=activityTotals(rows.filter(r=>r.activity.activityType===type));return <p key={type}>{labels[type]}: {num(totals.minutes)} min · {num(totals.distance)} km</p>;})}<p className="feature-note">Lifting volume is load × exact reps; bodyweight and ambiguous sets are excluded. Activity time is logged time, not full session duration.</p>{workouts.map(w=><Button key={w.id} variant="outline" className="feature-session-link" onClick={()=>onOpen(w.id)}>{w.name}<span>View session</span></Button>)}{!workouts.length&&<p className="feature-note">Nothing completed on this date.</p>}</div></details>;
}

export function WaistTracking({state,onSave}:{state:TrainingState;onSave:(entry:WaistEntry)=>void}){
 const [open,setOpen]=useState(false);const [date,setDate]=useState(localDate());const [value,setValue]=useState('');const [unit,setUnit]=useState('cm');
 const entries=(state.waistEntries??[]).filter(e=>!e.deletedAt).sort((a,b)=>b.date.localeCompare(a.date));
 const latest=entries.find(e=>e.date<=localDate());
 const edit=(d:string,cm?:number)=>{setDate(d);setValue(cm?String(numRaw(unit==='in'?cm/2.54:cm)):'');setOpen(true);};
 const save=()=>{const n=Number(value);if(!Number.isFinite(n)||n<=0||!validMeasurementDate(date)||date>localDate())return toast.error('Enter a positive measurement and a valid date up to today');const existing=(state.waistEntries??[]).find(e=>e.date===date);onSave({id:existing?.id??uid('waist'),date,cm:unit==='in'?n*2.54:n,updatedAt:new Date().toISOString()});setOpen(false);toast.success('Waist measurement saved');};
 return <details className="page-disclosure"><summary><span>Waist measurements<small>{latest?`${num(latest.cm)} cm · ${latest.date}`:'Optional · track alongside bodyweight'}</small></span><ChevronDown/></summary><div className="feature-panel"><Button variant="outline" onClick={()=>edit(localDate(),entries.find(e=>e.date===localDate())?.cm)}>Log waist</Button><p className="feature-note">Use the same measuring position and conditions each time. One entry per date; re-logging corrects it.</p>{entries.length>1&&<p>Change from first logged entry: {num(entries[0].cm-entries[entries.length-1].cm)} cm</p>}{entries.map(e=><div key={e.id} className="feature-measurement"><span>{e.date}<strong>{num(e.cm)} cm</strong></span><Button variant="ghost" onClick={()=>edit(e.date,e.cm)}>Edit</Button><Button variant="ghost" onClick={()=>{onSave({...e,deletedAt:new Date().toISOString(),updatedAt:new Date().toISOString()});toast('Measurement removed',{action:{label:'Undo',onClick:()=>onSave({...e,deletedAt:undefined,updatedAt:new Date().toISOString()})}});}}>Remove</Button></div>)}</div><Dialog open={open} onOpenChange={setOpen}><DialogContent className="border-white/10 bg-[#151713] text-white"><DialogHeader><DialogTitle>Log waist</DialogTitle><DialogDescription>Saved with your training data and backups.</DialogDescription></DialogHeader><label className="field-label">Date<Input type="date" value={date} max={localDate()} onChange={e=>setDate(e.target.value)}/></label><div className="feature-fields"><label className="field-label">Measurement<Input inputMode="decimal" value={value} onChange={e=>setValue(e.target.value)}/></label><label className="field-label">Unit<NativeSelect value={unit} onChange={e=>{const next=e.target.value;const n=Number(value);if(n>0)setValue(String(numRaw(next==='in'?n/2.54:n*2.54)));setUnit(next);}}><NativeSelectOption value="cm">cm</NativeSelectOption><NativeSelectOption value="in">inches</NativeSelectOption></NativeSelect></label></div><Button onClick={save} className="bg-[var(--lime)] text-black">Save measurement</Button></DialogContent></Dialog></details>;
}
const numRaw=(n:number)=>Number(n.toFixed(2));

export function MonthlyReview({state}:{state:TrainingState}){
 const [month,setMonth]=useState(localDate().slice(0,7));
 const months=[...new Set([localDate().slice(0,7),...state.workouts.filter(w=>w.status==='completed').map(w=>w.date.slice(0,7)),...state.bodyweightEntries.map(e=>e.date.slice(0,7))])].sort().reverse();
 const workouts=state.workouts.filter(w=>w.status==='completed'&&w.date.startsWith(month)&&w.date<=localDate());
 const filtered={...state,workouts};
 const records=[...strengthRecords(filtered,state.settings.defaultUnit).entries()];
 const rows=activityRows(filtered);const types=[...new Set(rows.map(r=>r.activity.activityType))];
 const weights=state.bodyweightEntries.filter(e=>e.date.startsWith(month)&&e.date<=localDate()).sort((a,b)=>a.date.localeCompare(b.date));
 const days=new Set(workouts.map(w=>w.date)).size;
 const sets=workouts.flatMap(w=>w.exercises.flatMap(e=>e.sets.filter(s=>s.completed&&!s.warmup))).length;
 const volume=num(workouts.reduce((sum,w)=>sum+workoutLiftingVolume(w,state.settings.defaultUnit).volume,0));
 const activities=types.map(type=>({type,totals:activityTotals(rows.filter(r=>r.activity.activityType===type))}));
 const bodyweight=weights.length?`${num(convertWeight(weights[0].weight,weights[0].unit,state.settings.defaultUnit))} → ${num(convertWeight(weights.at(-1)!.weight,weights.at(-1)!.unit,state.settings.defaultUnit))} ${state.settings.defaultUnit}`:null;
 const text=[`TRAINING REVIEW — ${month}`,`${workouts.length} completed session${workouts.length===1?"":"s"} on ${days} day${days===1?"":"s"}`,`${sets} working set${sets===1?"":"s"}`,`Lifting volume: ${volume} ${state.settings.defaultUnit} (exact loaded reps; excludes warm-ups)`,...activities.map(({type,totals:t})=>`${labels[type]}: ${num(t.minutes)} min · ${num(t.distance)} km${type==='ruck'?` · ${num(t.ruckKgKm)} kg·km`:''}`),...(records.length?['Best main-lift sets this month:',...records.map(([name,r])=>`${name}: ${r.display}`)]:[]),...(bodyweight?[`Bodyweight: ${bodyweight} (${weights.length} measurements)`]:[])].join('\n');
 return <details className="page-disclosure monthly-review"><summary><span>Monthly review<small>Completed training · copyable summary</small></span><ChevronDown/></summary><div className="feature-panel monthly-review-panel"><div className="monthly-review-controls"><label className="field-label">Month<NativeSelect value={month} onChange={e=>setMonth(e.target.value)} aria-label="Review month" className="monthly-month-select">{months.map(value=><NativeSelectOption value={value} key={value}>{new Intl.DateTimeFormat(undefined,{month:'long',year:'numeric',timeZone:'UTC'}).format(new Date(`${value}-01T12:00:00Z`))}</NativeSelectOption>)}</NativeSelect></label><Button variant="outline" onClick={async()=>{try{await navigator.clipboard.writeText(text);toast.success('Review copied');}catch{toast.error('Could not copy. Select the summary text to copy it.');}}}>Copy</Button></div><div className="monthly-review-stats"><div><strong>{workouts.length}</strong><span>sessions · {days} days</span></div><div><strong>{sets}</strong><span>working sets</span></div><div><strong>{volume} {state.settings.defaultUnit}</strong><span>lifting volume</span></div></div>{activities.length>0&&<div className="monthly-review-section"><h3>Activities</h3><div className="monthly-review-activities">{activities.map(({type,totals:t})=><div key={type}><strong>{labels[type]}</strong><span>{[t.minutes>0?`${num(t.minutes)} min`:null,t.distance>0?`${num(t.distance)} km`:null,type==='ruck'&&t.ruckKgKm>0?`${num(t.ruckKgKm)} kg·km`:null].filter(Boolean).join(' · ')||'Logged'}</span></div>)}</div></div>}{records.length>0&&<div className="monthly-review-section"><h3>Best main-lift sets</h3><div className="monthly-review-records">{records.map(([name,r])=><p key={name}><span>{name}</span><strong>{r.display}</strong></p>)}</div></div>}{bodyweight&&<p className="monthly-review-weight">Bodyweight <strong>{bodyweight}</strong> · {weights.length} measurements</p>}{!workouts.length&&!weights.length&&<p className="feature-note">No completed training or bodyweight entries in this month.</p>}<p className="monthly-review-footnote">Lifting volume counts exact loaded reps and excludes warm-ups. Activity time is logged time.</p></div></details>;
}
